/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lq1taPfLqoF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from 'next/image'
import { getHomePage } from "@/lib/api";
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import { TestimonialCard } from './testimonial-card';
import { draftMode } from 'next/headers';
import { ContentfulImage } from '@/types/contentful';

interface Testimonial {
  avatar: ContentfulImage;
  name: string;
  quote: string;
}

export async function LandingPage() {
  const { isEnabled } = draftMode();
  const homePage = await getHomePage(isEnabled);
  const testimonials = homePage?.testimonialsCollection?.items || [];
  console.log(testimonials);
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  {homePage.heroTitle}
                </h1>
                <div className="max-w-[600px] text-primary-foreground/80 md:text-xl">
                  {documentToReactComponents(homePage.heroText?.json)}
                </div>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                {homePage.callToAction1 && (
                  <Link
                    href={homePage.callToAction1.link}
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary-foreground px-8 text-sm font-medium text-primary shadow transition-colors hover:bg-primary-foreground/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    {homePage.callToAction1.text}
                  </Link>)}
                {homePage.callToAction2 && (
                  <Link
                    href={homePage.callToAction2.link}
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-primary text-primary-foreground px-8 text-sm font-medium shadow-sm transition-colors hover:bg-primary-foreground/10 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    {homePage.callToAction2.text}
                  </Link>)}
              </div>
            </div>
            <Image
              src="/logo-big.png"
              width={550}
              height={550}
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-contain sm:w-full lg:order-last lg:aspect-square"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-muted-foreground">
                Amenities
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Unparalleled Aquatic Facilities</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Discover our state-of-the-art pools, saunas, and wellness centers designed to elevate your swimming
                experience.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <img
              src="/placeholder.svg"
              width="550"
              height="310"
              alt="Amenities"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            />
            <div className="flex flex-col justify-center space-y-4">
              <ul className="grid gap-6">
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Olympic-Size Pool</h3>
                    <p className="text-muted-foreground">Train like a pro in our world-class 50-meter pool.</p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Heated Jacuzzi</h3>
                    <p className="text-muted-foreground">Relax and unwind in our luxurious heated jacuzzi.</p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Sauna and Steam Room</h3>
                    <p className="text-muted-foreground">
                      Rejuvenate your body and mind in our saunas and steam rooms.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-background px-3 py-1 text-sm text-muted-foreground">
                Testemuñas
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                {homePage.testimonialsTitle}
              </h2>
              <div className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                {documentToReactComponents(homePage.testimonialsDescription?.json)}
              </div>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-stretch gap-6 py-12 lg:grid-cols-3 lg:gap-12">
            {
              testimonials?.length > 0 && testimonials
                .map((testimonial: Testimonial) =>
                  testimonial.name && testimonial.quote && (
                    <TestimonialCard name={testimonial.name} quote={testimonial.quote} avatar={testimonial.avatar?.url} />
                  )
                )
            }
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-muted-foreground">
                Eventos
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                {homePage.eventsTitle}
              </h2>
              <div className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                {documentToReactComponents(homePage.eventsDescription?.json)}
              </div>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <Image
              src={homePage.eventsImage?.url || "/placeholder.svg"}
              width={550}
              height={310}
              alt={homePage.eventsImage?.title || "Eventos"}
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            />
            <div className="flex flex-col justify-center space-y-4">
              <ul className="grid gap-6">
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Swim Clinic</h3>
                    <p className="text-muted-foreground">
                      Join our expert coaches for a comprehensive swim clinic to improve your technique.
                    </p>
                    <div className="flex items-center text-muted-foreground">
                      <CalendarDaysIcon className="mr-2 h-4 w-4" />
                      <span>June 15, 2023</span>
                    </div>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Aqua Fitness Challenge</h3>
                    <p className="text-muted-foreground">
                      Compete in our exciting Aqua Fitness Challenge and win great prizes.
                    </p>
                    <div className="flex items-center text-muted-foreground">
                      <CalendarDaysIcon className="mr-2 h-4 w-4" />
                      <span>July 20, 2023</span>
                    </div>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Summer Pool Party</h3>
                    <p className="text-muted-foreground">
                      Join us for a fun-filled summer pool party with music, food, and games.
                    </p>
                    <div className="flex items-center text-muted-foreground">
                      <CalendarDaysIcon className="mr-2 h-4 w-4" />
                      <span>August 5, 2023</span>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

function CalendarDaysIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}

